import type { NextPage } from 'next';
import Head from 'next/head';
import Dataviz from '../components/Dataviz/Dataviz';
import { data } from '../constants/data';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Dataviz
            data={data}
          />
      </main>

    </div>
);

export default Home;
